### PR TITLE
Locale support + PolyZone & Target conversion

### PR DESCRIPTION
**Pull request by Sna-aaa**
Refactoring,
Support for locales
Add zones and target

### CODE REVIEW

**Comment by DannysRP** [comment]
There is no way to store the vehicle once you are done

**Comment by Sna-aaa** [comment]
Corrected, marker created

**Comment by DannysRP** [comment]
Maybe have a draw text show up to open the garage and delete vehicles. As it is right now if you run into the zone it will open the garage menu. If you back your truck into the zone it will just delete it.

**Comment by Sna-aaa** [comment]
As the whole point of those modifications are to remove drawtext and i found a workaround to do it i will not put them back. Some people are better to look at their screen when playing :)

**Comment by DannysRP** [comment]
I'm not talking about DrawText3D. I'm talking about using the new QBCore draw text that most of these other resources are using with the updates to PZ/Target

**Pull request merged**
